[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
mit = "7zF2xa5P22ahMqdQYo9P4kjD4qxvUy5hGozmk8DyB3iz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/trankhacvy/.config/solana/id.json"
